### ISSUE TITLE
NFS Undercover's patched versions can't be unpacked

### ISSUE THREAD

**Issue by BreakinBenny** [NFSTools/YAMLDatabase#13]
This was tested on the Origin version, 1.1.2.1. It might occur on 1.0.1.17 and 1.0.1.18 as well, but at least those are easy to update to. (The latter has the Challenge Series Expansion.)
```
C:\GAMES\NFS WORLD\Attribulator_Windows>attribulator.cli unpack -i "D:\Origin Games\Need for Speed Undercover\GLOBAL" -o "D:\Origin Games\NFSUC" -p UNDERCOVER -f yml
[00:17:39 INF] Loading database from disk...
[00:17:40 ERR] An error occurred while running the application.
System.Collections.Generic.KeyNotFoundException: Type '0x954FC25B' is not registered for game GLOBAL
   at VaultLib.Core.TypeRegistry.ResolveType(String gameId, String typeId)
   at VaultLib.Core.TypeRegistry.ResolveType(String gameId, String typeId)
   at VaultLib.Core.TypeRegistry.CreateInstance(String gameId, VltClass vltClass, VltClassField vltClassField, VltCollection collection)
   at VaultLib.ModernBase.Exports.ClassLoad.ReadPointerData(Vault vault, BinaryReader br)
   at VaultLib.Core.DB.Database.ReadExports(Vault vault, BinaryReader vltStreamReader, BinaryReader binStreamReader)
   at VaultLib.Core.DB.Database.LoadVault(Vault vault, VaultLoadingWrapper loadingWrapper)
   at VaultLib.Core.Pack.StandardVaultPack.Load(BinaryReader br, Database database, PackLoadingOptions loadingOptions)
   at Attribulator.Plugins.SpeedProfiles.UndercoverProfile.<>c__DisplayClass0_0.<LoadFiles>b__3(<>f__AnonymousType2`2 <>h__TransparentIdentifier2) in D:\a\Attribulator\Attribulator\Attribulator.Plugins.SpeedProfiles\UndercoverProfile.cs:line 22
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Attribulator.Plugins.SpeedProfiles.UndercoverProfile.LoadFiles(Database database, String directory) in D:\a\Attribulator\Attribulator\Attribulator.Plugins.SpeedProfiles\UndercoverProfile.cs:line 18
   at Attribulator.CLI.Commands.UnpackCommand.Execute() in D:\a\Attribulator\Attribulator\Attribulator.CLI\Commands\UnpackCommand.cs:line 55
   at Attribulator.CLI.Program.<>c__DisplayClass1_0.<RunApplication>b__0(BaseCommand cmd) in D:\a\Attribulator\Attribulator\Attribulator.CLI\Program.cs:line 68
   at CommandLine.ParserResultExtensions.MapResult[T1,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 notParsedFunc)
   at Attribulator.CLI.Program.RunApplication(IServiceProvider serviceProvider, IEnumerable`1 args) in D:\a\Attribulator\Attribulator\Attribulator.CLI\Program.cs:line 64
```

**Comment by BreakinBenny** [comment]
Nope, it affects 1.0.0.1 as well
